apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy   # "admin" (base64 encoded)
  mongo-passsword: bW9uZ29wYXNzd29yZA==  # "password123" (base64 encoded)